### ISSUE TITLE
Missing images in algorithm explanation

### ISSUE THREAD

**Issue by AdamTas** [JustWhit3/SAFD-algorithm#4]
Images are missing from 
https://github.com/JustWhit3/SAFD-algorithm/blob/main/doc/algorithm_explanation.md

**Comment by JustWhit3** [comment]
Hi @AdamTas thanks a lot for this issue. The problem is not of the documentation, but of the [Latex equation editor server](https://latex.codecogs.com/), which seems temporarily off. I'll wait a few days, if the servers will not  turn on again, I will use another Latex equation editor for markdown.

@all-contributors please add @AdamTas for review
