### ISSUE TITLE
A quick review and comments.

### ISSUE THREAD

**Issue by patlefort** [JustWhit3/SAFD-algorithm#5]
Hi, after a quick glance at your code, a few easy improvements can be made:

- Never ever use `using namespace std;`.
- For your constants, use `inline constexpr`.
- For the tab and ax variables, it is unnecessary to store them outside the stack. Just declare then locally in your function. On linux, you have 8 mb of stack space by default, more than enough.
- `IsInBounds`: Unnecessary template. Since it's only used for tests, you could simply define(implement) it in a header in your test directory.

**Comment by JustWhit3** [comment]
Hi @patlefort thanks for the issue, I will answer you step-by-step to your statements:

- I am not in agreement with the `namespace` usage. Well, yes, I never ever use this directive inside an header or a library, since this could be a big problem and there would be problems in the recognition of some variables from other libraries which could have the same name. But since I am using this directive inside a `main.cpp` program which is executed and never included inside another library / program, why should I care about not using the namespace `std`? It is common practice in my work to use this directive if I am in a main program, therefore, in this precise case, your first issue is opinion-based.
- Why should I use `inline constexpr` if my constant variables are firstly declared in a .h file and then defined in a .cpp file? Defining them as extern constant shouldn't be enough?
- Yes you are right, I did this in order to avoid redeclaring the same variables many times if the function is called more than one time. I think it is not a big problem however, right?.
- This is true also, but it is not an issue. I simply defined this function in another project and tested it there. Then, I toke it from that project and put in this program. I usually keep all my functions in an utils file, just for convenience. I understand it would have been better to redefine this as a non-template, but, I repeat, for me this is not an issue, but an opinion-based problem.

**Comment by patlefort** [comment]
using namespace std is a bad practice anywhere, it is an established fact in c++, ask any c++ experts. Too many possible problems that only a c++ expert could understand and they aren't worth the risk ever. If it's common practice in your work, then there is a problem of learning c++. There is a lot of bad, outdated resources that still uses the directive unfortunately and many people fall into the trap.

About `inline constexpr`, it's easier because you can simply put in your .h file for example `inline constexpr double STEP_SIZE = cbrt( __DBL_EPSILON__ );`, no need to have a declaration in your .h file and a definition in your cpp file and it will not break ODR. Also, being constexpr makes it a compile time constant and opens it for more optimizations. However, if it's only used in one cpp file, then you can put it only in that cpp file, no need to have it in the .h. `inline constexpr` should always be preferred for constants, it is simply better, unless that constant needs to have its symbol exported in a shared library.

On my third point, it's another can of worm that's better not to open. It make code messier, makes functions not re-entrant or thread-safe, can be worst for performance, better to never do that unless it's really too big to fit in the stack. Yes it's an opinion, but c++ allows you to do about anything you want, it allows you to shoot yourself in the foot, but the pain might start much later down the line, when it's too late.

I don't want to sound harsh or antagonistic, but these are "opinions" based on decades of programming experience that I'm sharing with you to help.

**Comment by JustWhit3** [comment]
Could you please explain me why using namespaces directives is always a bad practice, also in main and test files? thanks, it is useful also for me to learn every day something new.

Ok, thanks for all the  other suggestions, I will have a look at them in the next days.

**Comment by patlefort** [comment]
[ISO C++ coding standard on using namespace std](https://isocpp.org/wiki/faq/coding-standards#using-namespace-std).
[Plenty of discussion on that on stack overflow](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice).
[Stop Using using namespace](https://www.youtube.com/watch?v=MZqjl9HEPZ8) (I recommend his channel)

In short: It import many more names than you'd expect and can cause name collision or overloading issues and it makes code less readable,

**Comment by JustWhit3** [comment]
Thanks a lot for this information. I will update my code soon with some of the things you suggested me.

@all-contributors please add @patlefort for ideas
